import "@/node_modules/react-modal-video/css/modal-video.css";
import "leaflet/dist/leaflet.css";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/free-mode";
import "@/public/assets/css/style.css";
import "@/public/assets/css/custom.css";

import { urbanist, mulish, dM_Sans } from "@/lib/font";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing, DEFAULT_LOCALE } from "@/i18n/routing";

import IntlReduxProviderWrapper from "./IntlReduxProviderWrapper";

export const metadata = {
  title: "Counsolve React Template",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }) {
  const locale = params?.locale || DEFAULT_LOCALE;

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages({ locale });

  return (
    <html
      lang={locale}
      className={`${mulish.variable} ${urbanist.variable} ${dM_Sans.variable}`}
      suppressHydrationWarning
    >
      <body>
        <IntlReduxProviderWrapper locale={locale} messages={messages}>
          {children}
        </IntlReduxProviderWrapper>
      </body>
    </html>
  );
}
